name = "MLMD"
grammar = "mlmd"
path_suffixes = ["mlmd"]
line_comments = ["# "]
brackets = [
  { start = "(", end = ")", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = false },
]
