/// Generate a boilerplate block plugin Rust source file (native .so/.dylib).
///
/// The generated file implements the `Plugin` trait with stub `infer_shape`,
/// `param_count`, and `codegen` methods. Registration is handled automatically
/// via the `register_plugin!` macro, and the FFI export via `export_plugin!`.
///
/// # Arguments
/// * `block_name` - The PascalCase block type name (e.g., "MyCustomLayer")
///
/// # Returns
/// The generated Rust source code as a String.
pub fn generate_plugin_file(block_name: &str) -> String {
    let snake = to_snake_case(block_name);

    format!(
        r#"/// {name} block plugin
///
/// Auto-generated by `mlmd plugin new`.
/// Fill in the shape inference and codegen implementations.

use mlmd_plugin_api::*;

struct {name};

impl Plugin for {name} {{
    fn name(&self) -> &'static str {{ "{name}" }}

    fn params(&self) -> Vec<ParamSpec> {{
        vec![
            // TODO: Add your params here
            // ParamSpec::number("input_dim").required(),
        ]
    }}

    fn infer_shape(&self, inputs: &[Shape], _params: &HashMap<String, ParamValue>) -> Result<Vec<Shape>, String> {{
        if inputs.is_empty() {{
            return Err("{name} requires at least one input".to_string());
        }}
        // TODO: Implement shape inference logic
        Ok(vec![inputs[0].clone()]) // Passthrough by default
    }}

    fn param_count(&self, _inputs: &[Shape], _params: &HashMap<String, ParamValue>) -> Option<usize> {{
        // TODO: Compute parameter count if applicable
        None
    }}

    fn codegen(&self, target: &str, block: &Block, input_vars: &[String], output_vars: &[String]) -> Option<BlockCodegenResult> {{
        match target {{
            "pytorch" => Some(BlockCodegenResult::stateless(
                format!("{{}} = {{}}", output_vars[0], input_vars[0]),
            )),
            "keras" => Some(BlockCodegenResult::stateless(
                format!("{{}} = {{}}", output_vars[0], input_vars[0]),
            )),
            "candle" => Some(BlockCodegenResult::stateless(
                format!("{{}} = {{}}", output_vars[0], input_vars[0]),
            )),
            _ => None,
        }}
    }}
}}

register_plugin!({name});
export_plugin!({name});

#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn test_{snake}_shape_inference() {{
        let plugin = {name};
        let params = HashMap::new();
        let result = plugin.infer_shape(&[vec![3, 32, 32]], &params);
        assert!(result.is_ok());
    }}
}}
"#,
        name = block_name,
        snake = snake,
    )
}

/// Generate a boilerplate block plugin Rust source file for WASM target.
///
/// Same as `generate_plugin_file` but uses `export_wasm_plugin!` instead of
/// `export_plugin!` for WASM-compatible exports.
pub fn generate_plugin_file_wasm(block_name: &str) -> String {
    let snake = to_snake_case(block_name);

    format!(
        r#"/// {name} block plugin (WASM)
///
/// Auto-generated by `mlmd plugin init --wasm`.
/// Fill in the shape inference and codegen implementations.
///
/// Build:
///   rustup target add wasm32-wasi
///   cargo build --target wasm32-wasi --release

use mlmd_plugin_api::*;

struct {name};

impl Plugin for {name} {{
    fn name(&self) -> &'static str {{ "{name}" }}

    fn params(&self) -> Vec<ParamSpec> {{
        vec![
            // TODO: Add your params here
            // ParamSpec::number("input_dim").required(),
        ]
    }}

    fn infer_shape(&self, inputs: &[Shape], _params: &HashMap<String, ParamValue>) -> Result<Vec<Shape>, String> {{
        if inputs.is_empty() {{
            return Err("{name} requires at least one input".to_string());
        }}
        // TODO: Implement shape inference logic
        Ok(vec![inputs[0].clone()]) // Passthrough by default
    }}

    fn param_count(&self, _inputs: &[Shape], _params: &HashMap<String, ParamValue>) -> Option<usize> {{
        // TODO: Compute parameter count if applicable
        None
    }}

    fn codegen(&self, target: &str, block: &Block, input_vars: &[String], output_vars: &[String]) -> Option<BlockCodegenResult> {{
        match target {{
            "pytorch" => Some(BlockCodegenResult::stateless(
                format!("{{}} = {{}}", output_vars[0], input_vars[0]),
            )),
            "keras" => Some(BlockCodegenResult::stateless(
                format!("{{}} = {{}}", output_vars[0], input_vars[0]),
            )),
            "candle" => Some(BlockCodegenResult::stateless(
                format!("{{}} = {{}}", output_vars[0], input_vars[0]),
            )),
            _ => None,
        }}
    }}
}}

register_plugin!({name});
export_wasm_plugin!({name});

#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn test_{snake}_shape_inference() {{
        let plugin = {name};
        let params = HashMap::new();
        let result = plugin.infer_shape(&[vec![3, 32, 32]], &params);
        assert!(result.is_ok());
    }}
}}
"#,
        name = block_name,
        snake = snake,
    )
}

/// Generate a `Cargo.toml` for a new plugin project.
///
/// The generated template depends on `mlmd-plugin-api` and `mlmd-core` via
/// relative paths.  You may need to adjust these paths depending on where
/// mlmd lives in your project.
///
/// # Arguments
/// * `plugin_name` - The kebab-case package name (e.g. "my-cool-plugin")
/// * `block_name` - The PascalCase block type name (e.g. "MyCoolLayer")
pub fn generate_plugin_cargo_toml(plugin_name: &str, block_name: &str) -> String {
    format!(
        r#"[package]
name = "{plugin_name}"
version = "0.1.0"
edition = "2021"
description = "NNML block plugin: {block_name}"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
# TODO: Update these paths to point to your local mlmd checkout, or use
# published versions from crates.io once available.
mlmd-core = {{ path = "../mlmd-core" }}
mlmd-plugin-api = {{ path = "../mlmd-plugin-api" }}
"#,
        plugin_name = plugin_name,
        block_name = block_name,
    )
}

/// Convert a kebab-case string to PascalCase.
///
/// # Examples
///
/// ```
/// use mlmd_core::plugin::scaffold::kebab_to_pascal;
/// assert_eq!(kebab_to_pascal("my-cool-plugin"), "MyCoolPlugin");
/// assert_eq!(kebab_to_pascal("mlmd-example-plugin"), "MlmdExamplePlugin");
/// ```
pub fn kebab_to_pascal(s: &str) -> String {
    s.split('-')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().to_string() + chars.as_str(),
            }
        })
        .collect()
}

/// Convert a PascalCase string to snake_case.
///
/// # Examples
///
/// ```
/// use mlmd_core::plugin::scaffold::to_snake_case;
/// assert_eq!(to_snake_case("MyCustomLayer"), "my_custom_layer");
/// assert_eq!(to_snake_case("AttentionHead"), "attention_head");
/// assert_eq!(to_snake_case("ValidBlock"), "valid_block");
/// ```
pub fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_lowercase().next().unwrap());
        } else {
            result.push(c);
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_simple_block() {
        let code = generate_plugin_file("MyCustomLayer");
        assert!(code.contains("MyCustomLayer"));
        assert!(code.contains("infer_shape"));
        assert!(code.contains("register_plugin!(MyCustomLayer)"));
        assert!(code.contains("fn codegen("));
    }

    #[test]
    fn test_generate_snake_case_name() {
        let code = generate_plugin_file("AttentionHead");
        assert!(code.contains("AttentionHead"));
        assert!(code.contains("attention_head"));
    }

    #[test]
    fn test_generate_valid_rust() {
        // Verify the generated code uses the new Plugin trait pattern
        let code = generate_plugin_file("ValidBlock");
        assert!(code.contains("impl Plugin for ValidBlock"));
        assert!(code.contains("register_plugin!(ValidBlock)"));
    }

    #[test]
    fn test_to_snake_case_basic() {
        assert_eq!(to_snake_case("MyCustomLayer"), "my_custom_layer");
    }

    #[test]
    fn test_to_snake_case_single_word() {
        assert_eq!(to_snake_case("Linear"), "linear");
    }

    #[test]
    fn test_to_snake_case_acronym() {
        assert_eq!(to_snake_case("LSTM"), "l_s_t_m");
    }

    #[test]
    fn test_kebab_to_pascal_basic() {
        assert_eq!(kebab_to_pascal("my-cool-plugin"), "MyCoolPlugin");
    }

    #[test]
    fn test_kebab_to_pascal_single() {
        assert_eq!(kebab_to_pascal("plugin"), "Plugin");
    }

    #[test]
    fn test_kebab_to_pascal_trailing_hyphen() {
        assert_eq!(kebab_to_pascal("my-plugin-"), "MyPlugin");
    }

    #[test]
    fn test_generate_cargo_toml() {
        let toml = generate_plugin_cargo_toml("my-cool-plugin", "MyCoolPlugin");
        assert!(toml.contains(r#"name = "my-cool-plugin""#));
        assert!(toml.contains("mlmd-core"));
        assert!(toml.contains("mlmd-plugin-api"));
        assert!(toml.contains("cdylib"));
    }
}
