/// Generate a boilerplate block plugin Rust source file.
///
/// The generated file implements the BlockDef trait with stub infer_shape,
/// param_count, and codegen functions for all 3 targets (pytorch, keras, candle).
///
/// # Arguments
/// * `block_name` - The PascalCase block type name (e.g., "MyCustomLayer")
///
/// # Returns
/// The generated Rust source code as a String.
pub fn generate_plugin_file(block_name: &str) -> String {
    let snake = to_snake_case(block_name);

    format!(
        r#"/// {name} block plugin
///
/// Auto-generated by `mlmd plugin new`.
/// Fill in the shape inference and codegen implementations.

use mlmd_core::ast::graph::{{Block, Shape}};
use mlmd_core::ast::nodes::ParamValue;
use mlmd_core::block::types::{{BlockDef, ParamSpec, ParamType}};
use mlmd_core::block::registry::register_block;
use mlmd_core::codegen::result::BlockCodegenResult;
use mlmd_core::plugin::registry::register_block_codegen;
use std::collections::HashMap;

pub fn register() {{
    register_block(Box::new({name}Def));
    register_block_codegen("{name}", "pytorch", pytorch_codegen);
    register_block_codegen("{name}", "keras", keras_codegen);
    register_block_codegen("{name}", "candle", candle_codegen);
}}

struct {name}Def;

impl BlockDef for {name}Def {{
    fn name(&self) -> &str {{ "{name}" }}

    fn params(&self) -> &[ParamSpec] {{
        &[
            // TODO: Add your params here
            // ParamSpec {{ name: "input_dim", param_type: ParamType::Number, required: true, default: None }},
        ]
    }}

    fn infer_shape(&self, inputs: &[Shape], _params: &HashMap<String, ParamValue>) -> Result<Vec<Shape>, String> {{
        if inputs.is_empty() {{
            return Err("{name} requires at least one input".to_string());
        }}
        // TODO: Implement shape inference logic
        Ok(vec![inputs[0].clone()]) // Passthrough by default
    }}

    fn param_count(&self, inputs: &[Shape], _params: &HashMap<String, ParamValue>) -> Option<usize> {{
        // TODO: Compute parameter count if applicable
        None
    }}
}}

fn pytorch_codegen(block: &Block, input_vars: &[String], output_vars: &[String]) -> BlockCodegenResult {{
    // TODO: Implement PyTorch codegen
    BlockCodegenResult {{
        init: None,
        forward: format!("{{}} = {{}}", output_vars[0], input_vars[0]),
    }}
}}

fn keras_codegen(block: &Block, input_vars: &[String], output_vars: &[String]) -> BlockCodegenResult {{
    // TODO: Implement Keras codegen
    BlockCodegenResult {{
        init: None,
        forward: format!("{{}} = {{}}", output_vars[0], input_vars[0]),
    }}
}}

fn candle_codegen(block: &Block, input_vars: &[String], output_vars: &[String]) -> BlockCodegenResult {{
    // TODO: Implement Candle codegen
    BlockCodegenResult {{
        init: None,
        forward: format!("{{}} = {{}}", output_vars[0], input_vars[0]),
    }}
}}

#[cfg(test)]
mod tests {{
    use super::*;
    use std::collections::HashMap;

    #[test]
    fn test_{snake}_shape_inference() {{
        let def = {name}Def;
        let params = HashMap::new();
        let result = def.infer_shape(&[vec![3, 32, 32]], &params);
        assert!(result.is_ok());
    }}
}}
"#,
        name = block_name,
        snake = snake,
    )
}

/// Convert a PascalCase string to snake_case.
///
/// # Examples
///
/// ```
/// use mlmd_core::plugin::scaffold::to_snake_case;
/// assert_eq!(to_snake_case("MyCustomLayer"), "my_custom_layer");
/// assert_eq!(to_snake_case("AttentionHead"), "attention_head");
/// assert_eq!(to_snake_case("ValidBlock"), "valid_block");
/// ```
pub fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_lowercase().next().unwrap());
        } else {
            result.push(c);
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_simple_block() {
        let code = generate_plugin_file("MyCustomLayer");
        assert!(code.contains("MyCustomLayer"));
        assert!(code.contains("infer_shape"));
        assert!(code.contains("pytorch_codegen"));
        assert!(code.contains("keras_codegen"));
        assert!(code.contains("candle_codegen"));
    }

    #[test]
    fn test_generate_snake_case_name() {
        let code = generate_plugin_file("AttentionHead");
        assert!(code.contains("AttentionHead"));
        assert!(code.contains("attention_head"));
    }

    #[test]
    fn test_generate_valid_rust() {
        // Verify the generated code is valid Rust by checking syntax basics
        let code = generate_plugin_file("ValidBlock");
        assert!(code.contains("pub fn register()"));
        assert!(code.contains("fn pytorch_codegen"));
    }

    #[test]
    fn test_to_snake_case_basic() {
        assert_eq!(to_snake_case("MyCustomLayer"), "my_custom_layer");
    }

    #[test]
    fn test_to_snake_case_single_word() {
        assert_eq!(to_snake_case("Linear"), "linear");
    }

    #[test]
    fn test_to_snake_case_acronym() {
        assert_eq!(to_snake_case("LSTM"), "l_s_t_m");
    }
}
