# This file was generated by mlmd. Do not edit.

import pytest
import tensorflow as tf
from Attention_keras import build_model


def test_build_model():
    model = build_model()
    x = tf.random.normal((1, 512, 64,))
    x2 = tf.random.normal((1, 512, 64,))
    x3 = tf.random.normal((1, 512, 64,))
    output = model(x, x2, x3, training=False)
    assert output.shape == (1, 512, 64,)
