# This file was generated by mlmd. Do not edit.

import pytest
import torch
from Attention_pytorch import Attention


def test_forward():
    model = Attention()
    model.eval()
    x = torch.randn(1, 512, 64)
    x2 = torch.randn(1, 512, 64)
    x3 = torch.randn(1, 512, 64)
    output = model(x, x2, x3)
    assert output.shape == torch.Size([1, 512, 64])
