# This file was generated by mlmd. Do not edit.

import pytest
import torch
from Inception_pytorch import Inception


def test_forward():
    model = Inception()
    model.eval()
    x = torch.randn(1, 192, 28, 28)
    output = model(x)
    assert output.shape == torch.Size([1, 256, 28, 28])
