# This file was generated by mlmd. Do not edit.

import pytest
import torch
from LeNet5_pytorch import LeNet5


def test_forward():
    model = LeNet5()
    model.eval()
    x = torch.randn(1, 1, 28, 28)
    output = model(x)
    assert output.shape == torch.Size([1, 10])
