# This file was generated by mlmd. Do not edit.

import pytest
import tensorflow as tf
from LeNet5_keras import build_model


def test_build_model():
    model = build_model()
    x = tf.random.normal((1, 1, 28, 28,))
    output = model(x, training=False)
    assert output.shape == (1, 10,)
