# This file was generated by mlmd. Do not edit.

import pytest
import tensorflow as tf
from ResNet50_keras import build_model


def test_build_model():
    model = build_model()
    x = tf.random.normal((1, 256, 56, 56,))
    output = model(x, training=False)
    assert output.shape == (1, 256, 56, 56,)
