# This file was generated by mlmd. Do not edit.

import torch
import torch.nn as nn
import torch.nn.functional as F


class ResNet50(nn.Module):
    def __init__(self):
        super().__init__()
        self.Conv2d_0 = nn.Conv2d(256, 64, 1, stride=1, padding=0)
        self.BatchNorm_0 = nn.BatchNorm2d(64)
        self.ReLU_0 = nn.ReLU()
        self.Conv2d_1 = nn.Conv2d(64, 64, 3, stride=1, padding=1)
        self.BatchNorm_1 = nn.BatchNorm2d(64)
        self.ReLU_1 = nn.ReLU()
        self.Conv2d_2 = nn.Conv2d(64, 256, 1, stride=1, padding=0)
        self.BatchNorm_2 = nn.BatchNorm2d(256)
        self.Conv2d_3 = nn.Conv2d(256, 256, 1, stride=1, padding=0)
        self.BatchNorm_3 = nn.BatchNorm2d(256)
        self.ReLU_2 = nn.ReLU()

    def forward(self, skip):
        # skip: input  # [256, 56, 56]
        x = self.Conv2d_0(skip)  # [64, 56, 56]
        x = self.BatchNorm_0(x)  # [64, 56, 56]
        x = self.ReLU_0(x)  # [64, 56, 56]
        x = self.Conv2d_1(x)  # [64, 56, 56]
        x = self.BatchNorm_1(x)  # [64, 56, 56]
        x = self.ReLU_1(x)  # [64, 56, 56]
        x = self.Conv2d_2(x)  # [256, 56, 56]
        main_out = self.BatchNorm_2(x)  # [256, 56, 56]
        x = self.Conv2d_3(skip)  # [256, 56, 56]
        skip_out = self.BatchNorm_3(x)  # [256, 56, 56]
        x = main_out + skip_out  # [256, 56, 56]
        x = self.ReLU_2(x)  # [256, 56, 56]
        return x  # [256, 56, 56]
