# This file was generated by mlmd. Do not edit.

import pytest
import torch
from ResNet50_pytorch import ResNet50


def test_forward():
    model = ResNet50()
    model.eval()
    x = torch.randn(1, 256, 56, 56)
    output = model(x)
    assert output.shape == torch.Size([1, 256, 56, 56])
