# This file was generated by mlmd. Do not edit.

import pytest
import torch
from UNet_pytorch import UNet


def test_forward():
    model = UNet()
    model.eval()
    x = torch.randn(1, 1, 64, 64)
    output = model(x)
    assert output.shape == torch.Size([1, 1, 64, 64])
