# This file was generated by mlmd. Do not edit.

import pytest
import tensorflow as tf
from UNet_keras import build_model


def test_build_model():
    model = build_model()
    x = tf.random.normal((1, 1, 64, 64,))
    output = model(x, training=False)
    assert output.shape == (1, 1, 64, 64,)
